import {AUDIO_EXTENSIONS,extensionOf,formatBytes,formatDuration,bitrateBucket,parseID3,parseWav,parseFlac,summarize,countsBy,csvEscape} from './core.js';

const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const els={folder:$('#folder'),files:$('#files'),cancel:$('#cancel'),status:$('#status'),progressText:$('#progressText'),progressBar:$('#progressBar'),warnings:$('#warnings'),overview:$('#overview'),search:$('#search'),formatFilter:$('#formatFilter'),qualityFilter:$('#qualityFilter'),chartStyle:$('#chartStyle'),clearFilters:$('#clearFilters'),exportCsv:$('#exportCsv'),exportJson:$('#exportJson'),rows:$('#rows'),rowCount:$('#rowCount'),healthGrid:$('#healthGrid'),insights:$('#insights')};
let tracks=[],filtered=[],cancelled=false;

function mediaMetadata(file){return new Promise(resolve=>{const url=URL.createObjectURL(file),a=document.createElement('audio');let done=false;const finish=(o={})=>{if(done)return;done=true;URL.revokeObjectURL(url);a.remove();resolve(o)};a.preload='metadata';a.src=url;a.onloadedmetadata=()=>finish({duration:Number.isFinite(a.duration)?a.duration:0});a.onerror=()=>finish({});setTimeout(()=>finish({}),6000)})}
async function readHead(file,bytes=768*1024){return file.slice(0,Math.min(file.size,bytes)).arrayBuffer()}
async function scanOne(file){const ext=extensionOf(file.name),base={name:file.name,path:file.webkitRelativePath||file.name,size:file.size,ext,format:ext.toUpperCase(),modified:file.lastModified||0,artwork:false};let parsed={};try{const head=await readHead(file);if(ext==='mp3')parsed=parseID3(head);else if(ext==='wav'||ext==='wave')parsed=parseWav(head);else if(ext==='flac')parsed=parseFlac(head)}catch(e){base.warning=`Header parse: ${e.message}`}let media={};if(!parsed.duration)media=await mediaMetadata(file);const duration=parsed.duration||media.duration||0,bitrate=parsed.bitrate||(duration?Math.round(file.size*8/duration/1000):0),lossless=parsed.lossless??['wav','wave','flac','aif','aiff'].includes(ext),title=parsed.title||file.name.replace(/\.[^.]+$/,'');return {...base,...parsed,title,duration,bitrate,lossless}}

async function runScan(list){cancelled=false;tracks=[];filtered=[];els.cancel.disabled=false;els.warnings.textContent='';const files=[...list].filter(f=>AUDIO_EXTENSIONS.has(extensionOf(f.name))),ignored=list.length-files.length;els.status.textContent=`Scanning ${files.length.toLocaleString()} audio files…`;if(ignored)els.warnings.textContent=`Ignored ${ignored} unsupported/non-audio file${ignored===1?'':'s'}.`;const failures=[];for(let i=0;i<files.length;i++){if(cancelled)break;try{tracks.push(await scanOne(files[i]))}catch(e){failures.push(`${files[i].name}: ${e.message}`)}const pct=files.length?((i+1)/files.length)*100:0;els.progressBar.style.width=`${pct}%`;els.progressText.textContent=`${i+1} / ${files.length}`;if(i%10===0)render()}els.cancel.disabled=true;els.status.textContent=cancelled?`Scan cancelled — ${tracks.length.toLocaleString()} tracks kept.`:`Scan complete — ${tracks.length.toLocaleString()} tracks.`;if(failures.length)els.warnings.textContent+=` ${failures.length} files could not be analyzed.`;render(true)}

function currentRows(){const q=els.search.value.trim().toLowerCase(),f=els.formatFilter.value,quality=els.qualityFilter.value;return tracks.filter(t=>{if(q&&![t.name,t.title,t.artist,t.album,t.genre,t.path].some(v=>String(v||'').toLowerCase().includes(q)))return false;if(f&&t.ext!==f)return false;if(quality==='lossless'&&!t.lossless)return false;if(quality==='lossy'&&t.lossless)return false;if(quality==='low'&&(!t.bitrate||t.bitrate>=192))return false;if(quality==='missing'&&t.artist&&t.genre&&t.year&&t.bpm&&t.key)return false;if(quality==='duplicate'&&!duplicateKey(t))return false;return true})}
function duplicateKey(t){const a=String(t.artist||'').trim().toLowerCase(),n=String(t.title||'').trim().toLowerCase();return a&&n?`${a}|${n}`:''}
function duplicateStats(rows){const m=new Map();for(const t of rows){const k=duplicateKey(t);if(k)m.set(k,(m.get(k)||0)+1)}const groups=[...m.values()].filter(v=>v>1);return {groups:groups.length,tracks:groups.reduce((a,v)=>a+v,0)}}
function stat(label,value){return `<div class="stat"><strong>${esc(value)}</strong><span>${esc(label)}</span></div>`}
function renderOverview(rows){const s=summarize(rows),avg=rows.length?rows.reduce((a,t)=>a+(t.duration||0),0)/rows.length:0;els.overview.innerHTML=[stat('Tracks',s.tracks.toLocaleString()),stat('Storage',formatBytes(s.totalBytes)),stat('Playback',formatDuration(s.totalDuration)),stat('Artists',s.artists.toLocaleString()),stat('Albums',s.albums.toLocaleString()),stat('Avg track',formatDuration(avg)),stat('Lossless',s.tracks?`${Math.round(s.lossless/s.tracks*100)}%`:'—')].join('')}

const chartColors=['#5f91c2','#87aacb','#436e98','#a3bed6','#2f5a82','#c4d5e5','#6d7f92','#94a4b5','#37516c','#dbe6f0'];
function topPairs(pairs,n=10){return pairs.filter(([k])=>String(k)!=='Unknown').slice(0,n)}
function renderChart(id,pairs,valueFormatter=v=>v){const root=$(id);if(!root)return;const use=topPairs(pairs,10),style=els.chartStyle?.value||'bars';if(!use.length){root.innerHTML='<p class="muted">No data yet.</p>';return}const max=Math.max(1,...use.map(x=>x[1]));if(style==='table'){root.innerHTML=`<table class="mini-table"><tbody>${use.map(([k,v])=>`<tr><td>${esc(k)}</td><td>${esc(valueFormatter(v))}</td></tr>`).join('')}</tbody></table>`;return}if(style==='donut'){const total=use.reduce((a,x)=>a+x[1],0);let acc=0;const stops=use.map(([,v],i)=>{const start=acc/total*100;acc+=v;const end=acc/total*100;return `${chartColors[i%chartColors.length]} ${start}% ${end}%`}).join(',');root.innerHTML=`<div class="donut-wrap"><div class="donut" style="background:conic-gradient(${stops})"><span>${esc(valueFormatter(total))}</span></div><div class="donut-legend">${use.map(([k,v],i)=>`<div><i style="background:${chartColors[i%chartColors.length]}"></i><span>${esc(k)}</span><b>${esc(valueFormatter(v))}</b></div>`).join('')}</div></div>`;return}root.innerHTML=use.map(([k,v],i)=>style==='lollipop'?`<div class="lollipop-row"><div class="barlabel" title="${esc(k)}">${esc(k)}</div><div class="lollipop-track"><span style="width:${Math.max(2,v/max*100)}%"><i style="background:${chartColors[i%chartColors.length]}"></i></span></div><div class="barvalue">${esc(valueFormatter(v))}</div></div>`:`<div class="barrow"><div class="barlabel" title="${esc(k)}">${esc(k)}</div><div class="bartrack"><div class="barfill" style="width:${Math.max(2,v/max*100)}%;background:${chartColors[i%chartColors.length]}"></div></div><div class="barvalue">${esc(valueFormatter(v))}</div></div>`).join('')}
function durationBucket(s){if(!s)return'Unknown';if(s<120)return'<2 min';if(s<240)return'2–4 min';if(s<360)return'4–6 min';if(s<600)return'6–10 min';return'10+ min'}
function folderName(t){const p=String(t.path||'');const parts=p.split('/');return parts.length>1?parts[0]:'Root / selected files'}
function decade(y){const n=Number(y);return n>=1900&&n<2200?`${Math.floor(n/10)*10}s`:'Unknown'}
function renderCharts(rows){renderChart('#chartFormat',countsBy(rows,'ext',v=>(v||'unknown').toUpperCase()));const storage=new Map();for(const t of rows){const k=(t.ext||'unknown').toUpperCase();storage.set(k,(storage.get(k)||0)+t.size)}renderChart('#chartStorage',[...storage.entries()].sort((a,b)=>b[1]-a[1]),formatBytes);renderChart('#chartBitrate',countsBy(rows,'bitrate',v=>bitrateBucket(v)));renderChart('#chartSample',countsBy(rows,'sampleRate',v=>v?`${(v/1000).toFixed(v%1000?1:0)} kHz`:'Unknown'));renderChart('#chartBpm',countsBy(rows,'bpm',v=>v?`${Math.floor(Number(v)/10)*10}–${Math.floor(Number(v)/10)*10+9}`:'Unknown'));renderChart('#chartKey',countsBy(rows,'key',v=>v||'Unknown'));renderChart('#chartGenre',countsBy(rows,'genre',v=>v||'Unknown'));renderChart('#chartDecade',countsBy(rows,'year',v=>decade(v)));renderChart('#chartDuration',countsBy(rows,'duration',v=>durationBucket(v)));renderChart('#chartBitDepth',countsBy(rows,'bitDepth',v=>v?`${v}-bit`:'Unknown'));renderChart('#chartChannels',countsBy(rows,'channels',v=>v===1?'Mono':v===2?'Stereo':v?`${v} ch`:'Unknown'));renderChart('#chartFolders',countsBy(rows,'path',(v,t)=>folderName(t)))}
function renderHealth(rows){const s=summarize(rows),d=duplicateStats(rows),items=[['Missing artist',s.missingArtist],['Missing genre',s.missingGenre],['Missing year',s.missingYear],['Missing BPM',s.missingBpm],['Missing key',s.missingKey],['Missing artwork',s.missingArtwork],['Low bitrate',rows.filter(t=>t.bitrate&&t.bitrate<192).length],['Possible duplicate groups',d.groups],['Unreadable warnings',rows.filter(t=>t.warning).length]];els.healthGrid.innerHTML=items.map(([l,v])=>`<div class="health-item"><strong>${v.toLocaleString()}</strong><span>${esc(l)}</span></div>`).join('')}
function modeValue(rows,key){const p=countsBy(rows,key,v=>v||'Unknown').filter(([k])=>k!=='Unknown')[0];return p?p[0]:'—'}
function renderInsights(rows){if(!els.insights)return;const years=rows.map(t=>Number(t.year)).filter(y=>y>=1900&&y<2200),artists=countsBy(rows,'artist',v=>v||'Unknown').filter(([k])=>k!=='Unknown'),oneHit=artists.filter(([,v])=>v===1).length,dups=duplicateStats(rows);const bpm=rows.map(t=>Number(t.bpm)).filter(v=>v>0);els.insights.innerHTML=[stat('Top artist',artists[0]?.[0]||'—'),stat('Top genre',modeValue(rows,'genre')),stat('Most common key',modeValue(rows,'key')),stat('Median-ish BPM',bpm.length?Math.round(bpm.sort((a,b)=>a-b)[Math.floor(bpm.length/2)]):'—'),stat('Oldest release',years.length?Math.min(...years):'—'),stat('Newest release',years.length?Math.max(...years):'—'),stat('One-track artists',oneHit.toLocaleString()),stat('Possible duplicate tracks',dups.tracks.toLocaleString())].join('')}
function td(v){return `<td>${esc(v??'—')}</td>`}
function renderTable(rows){els.rowCount.textContent=`${rows.length.toLocaleString()} of ${tracks.length.toLocaleString()} tracks`;els.rows.innerHTML=rows.slice(0,1500).map(t=>`<tr title="${esc(t.path)}">${td(t.title||t.name)}${td(t.artist)}${td(t.album)}${td(t.genre)}${td((t.ext||'').toUpperCase())}${td(t.bitrate?`${Math.round(t.bitrate)} kbps`:'—')}${td(t.sampleRate?`${t.sampleRate} Hz`:'—')}${td(t.bitDepth||'—')}${td(t.channels||'—')}${td(formatDuration(t.duration))}${td(t.bpm||'—')}${td(t.key||'—')}${td(formatBytes(t.size))}</tr>`).join('')}
function syncFormatOptions(){const val=els.formatFilter.value,exts=[...new Set(tracks.map(t=>t.ext).filter(Boolean))].sort();els.formatFilter.innerHTML='<option value="">All formats</option>'+exts.map(x=>`<option value="${esc(x)}">${esc(x.toUpperCase())}</option>`).join('');els.formatFilter.value=exts.includes(val)?val:''}
function render(full=false){filtered=currentRows();if(full)syncFormatOptions();renderOverview(filtered);renderCharts(filtered);renderHealth(filtered);renderInsights(filtered);renderTable(filtered)}
function download(name,type,text){const blob=new Blob([text],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportCsv(){const headers=['name','path','title','artist','album','genre','year','bpm','key','format','bitrate','sampleRate','bitDepth','channels','duration','size','lossless'];const lines=[headers.join(','),...filtered.map(t=>headers.map(h=>csvEscape(t[h]??(h==='format'?t.ext:''))).join(','))];download('trackstats.csv','text/csv;charset=utf-8',lines.join('\n'))}
function exportJson(){download('trackstats.json','application/json',JSON.stringify({schema:2,created:new Date().toISOString(),summary:summarize(filtered),tracks:filtered},null,2))}
els.folder.onchange=e=>runScan(e.target.files);els.files.onchange=e=>runScan(e.target.files);els.cancel.onclick=()=>cancelled=true;for(const e of [els.search,els.formatFilter,els.qualityFilter])e.addEventListener(e.tagName==='INPUT'?'input':'change',()=>render());els.chartStyle?.addEventListener('change',()=>render());els.clearFilters.onclick=()=>{els.search.value='';els.formatFilter.value='';els.qualityFilter.value='';render()};els.exportCsv.onclick=exportCsv;els.exportJson.onclick=exportJson;render(true);
